insert into user(user_id,bio,coin,email,icon,last_login,password,roles,user_type,username,video,views) values (1,'I am yanguo,a full-stack developer',100,'test@gmail.com','default-icon.png','2022/12/06',12345678,'ROLE_USER',0,'yanguo','//www.youtube.com/embed/2FeymQoKvrk?wmode=transparent',3345);
insert into user(user_id,bio,coin,email,icon,last_login,password,roles,user_type,username,video,views) values (2,'This is Pets Official',100,'test@gmail.com','dog-pic.png','2022/12/06',12345678,'ROLE_USER',0,'Pets Official','//www.youtube.com/embed/2FeymQoKvrk?wmode=transparent',3345);
insert into user(user_id,bio,coin,email,icon,last_login,password,roles,user_type,username,video,views) values (3,'This is Sports Official',100,'test@gmail.com','michael-jordan.png','2022/12/06',12345678,'ROLE_USER',0,'Sports Official','//www.youtube.com/embed/2FeymQoKvrk?wmode=transparent',3345);

insert into event(id,title,event_dis,cat,event_image_name,event_date,host_id,user_id,latitude,longitude,live,room_type) values (1,'Dogs familly','Have fun with cute doggies','Pet','dog-pic.png','2024/12/06',2,2,51.4,-0.2,0,0);
insert into event(id,title,event_dis,cat,event_image_name,event_date,host_id,user_id,latitude,longitude,live,room_type) values (2,'Cats life','My life with my cats','Pet','cat.png','2024/12/06',2,2,51.6,0.1,0,0);
insert into event(id,title,event_dis,cat,event_image_name,event_date,host_id,user_id,latitude,longitude,live,room_type) values (3,'Live House','The best music festival','Life,Other','pexels-teddy-yang-2263436.jpg','2024/12/06',1,1,51.4,0,0,0);
insert into event(id,title,event_dis,cat,event_image_name,event_date,host_id,user_id,latitude,longitude,live,room_type) values (4,'Sports weekend','3 VS 3 basketball gaming','Sport','basketball.jpg','2024/12/06',3,3,51.556,0.1,0,0);
insert into event(id,title,event_dis,cat,event_image_name,event_date,host_id,user_id,latitude,longitude,live,room_type) values (5,'Traveling UK','Welcome to Oxford! The city is home to the University of Oxford, the oldest university in the English-speaking world','Travel','oxford.jpg','2024/12/06',1,1,51.75,-1.27,0,0);
